import Head from 'next/head'
import LinkButton from '../components/LinkButton'

export default function Home() {
  return (
    <div className='grid min-h-screen bg-violet-900/20 text-white font-["Heebo"]'>
      <Head>
        <title>Rendo - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
      </Head>

      <header>
        {/* site logo */} 

        {/* github, linked in */}
      </header>

      <main className='grid content-start'>
        {/* hero */}
        <section className='grid min-h-[80vh]'>
          <div className='grid content-center px-5 pt-20 pb-10 w-full max-w-screen-lg text-center'>
            <p className=' font-extralight text-7xl '>
              Hello!
            </p>
            <p className='mt-3 text-3xl font-thin tracking-wider'>
              I am <span className='font-normal'>Rendo</span>, 
              <br />
              <span className='text-2xl'>a Web Developer</span>.
            </p>

            <img  
              src='img/space.svg'
              alt='space stuff chilling (literally lmao) on space'
              className='pt-14 justify-self-center w-10/12 max-w-[320px]'
            />
          </div>

          {/* moon curve */}
          <div className='self-end grid -mb-1 pt-10 overflow-hidden'>
            <img 
              aria-hidden='true'
              src='img/curve-sm.svg' 
              className='w-full rotate-180 moon-glow'
            />
          </div>
        </section>

        {/* skills */}
        <section className='grid bg-stone-200 text-black/80'>
          <div className='grid content-start gap-6 px-5 pt-14 pb-10'>
            <h2 className='font-light text-4xl tracking-wide'>Skills</h2>
            
            <div className='grid gap-2'>
              <h3 className='text-2xl tracking-wide'>
                My current toolset
              </h3>
              <p className='font-light text-xl tracking-wider leading-relaxed'>
                HTML, CSS, JavaScript, PHP, React.js, Next.js, Tailwind CSS, Laravel, Alpine.js, Git, GitHub, Visual Studio Code.
              </p>
            </div>

            <div className='grid gap-2'>
              <h3 className='text-2xl tracking-wide'>
                Known tools and skills
              </h3>
              <p className='font-light text-xl tracking-wider leading-relaxed'>
                C#, ASP.NET, MySQL, Android Development (Java), Java REST API, Vue.js, phpMyAdmin, Visual Studio, IntelliJ IDEA.
              </p>
            </div>

            <img 
              src='img/astronaut.svg'
              alt='an astronaut reading naugthy alien (oc) smutfics on the moon for extra immersion'
              className='mt-6 justify-self-center drop-shadow-lg w-3/4 max-w-[250px]'
            />
          </div>
        </section>

        {/* projects */}
        <section className='grid'>
          {/* moon curve */}
          <div className='self-end grid -mt-1 pb-10 overflow-hidden'>
            <img 
              aria-hidden='true'
              src='img/curve-sm.svg' 
              className='w-full moon-glow'
            />
          </div>

          <div className='grid content-start gap-6 px-5 py-10 w-full max-w-screen-lg'>
            <h2 className='font-light text-4xl tracking-wide'>
              Projects
            </h2>

            <div className='grid content-start gap-3'>
              <h3 className='font-extralight text-3xl'>
                Personal Works
              </h3>

              <ul className='grid content-start gap-10 tracking-wide'>
                <li className='grid gap-2'>
                  <h4 className='font-medium text-2xl'>
                    Konolist
                  </h4>
                  <p className='italic'>
                    A list web app simplified for your convenience.
                  </p>
                  <p>
                    This is my second finished project using Create React App and Tailwind CSS. The app is made to look like MS Todo, both Windows and Android vesions, for both desktop and mobile breakpoints respectively.
                  </p>
                  <p>
                    My first project that works as an installable Progressive Web App (PWA). The app fully works offline and also comes with a fancy introductory page.
                  </p>
                  <p>
                    User data is stored locally on local storage and is encrypted using CryptoJS.
                  </p>

                  <div className='grid grid-cols-2 gap-3 mt-3'>
                    <LinkButton 
                      text='View'
                      href='https://www.kono.cx/'
                    />
                    <LinkButton 
                      text='Source'
                      href='https://github.com/rendoruiz/kono-list'
                    />
                  </div>
                </li>

                <li className='grid gap-2'>
                  <h4 className='font-medium text-2xl'>
                    Hacker News
                  </h4>
                  <p className='italic'>
                    Browse Hacker News with Reddit's design and layout.
                  </p>
                  <p>
                    My second attempt on a Hacker News viewer and the goal this time is to faithfully mimic Reddit's looks even further for both mobile and desktop breakpoints.
                  </p>
                  <p>
                    This project is the first one I have finished using Next.js together with whole other libraries.
                  </p>
                  <p>
                    It is also my first project that has a dark mode switch built in.
                  </p>
                  <p>
                    However, it is not as performant as my first attempt when ran on Firefox and potentially WebKit-based browsers too.
                  </p>
                  
                  <div className='grid grid-cols-2 gap-3 mt-3'>
                    <LinkButton 
                      text='View'
                      href='https://news.knkd.app/'
                    />
                    <LinkButton 
                      text='Source'
                      href='https://github.com/rendoruiz/nextjs-hackernews'
                    />
                  </div>
                </li>

                <li className='grid gap-2'>
                  <h4 className='font-medium text-2xl'>
                    Readit News
                  </h4>
                  <p>
                    My first web app project at this scale created using Create React App.
                  </p>
                  <p>
                    Has support for home page, story page, and user page.
                  </p>
                  <p>
                    The goal for this project is to fully consume Hacker News' public API that is posted on GitHub.
                  </p>
                  <p>
                    It tries to mimic Reddit's desktop design and layout very loosely, but still responsive enough for mobile use.
                  </p>
                  
                  <div className='grid grid-cols-2 gap-3 mt-3'>
                    <LinkButton 
                      text='View'
                      href='https://old.news.knkd.app/'
                    />
                    <LinkButton 
                      text='Source'
                      href='https://github.com/rendoruiz/reactjs-hackernews'
                    />
                  </div>
                </li>

                <li className='grid gap-2'>
                  <h4 className='font-medium text-2xl'>
                    Recon Game Library
                  </h4>
                  <p>
                    An old Assembly 8086 project I once created for school a project.
                  </p>
                  <p>
                    The program starts with the home screen showing game selection menu for two games: Snake and Tic-Tac-Toe.
                  </p>
                  <p>
                    Made to run on emu8086 assembly emulator.
                  </p>
                  
                  <div className='grid mt-3'>
                    <LinkButton 
                      text='Source'
                      href='https://github.com/rendoruiz/asm8086-recongamelibrary'
                    />
                  </div>
                </li>
              </ul>
            </div>

            <div className='grid content-start gap-5 mt-3'>
              <div className='grid content-start'>
                <h3 className='font-extralight text-3xl'>
                  Sites I've worked on,
                </h3>
                <p className='mt-1 font-thin text-base leading-none tracking-widest'>
                  as the Web Developer.
                </p>
              </div>
              
              <ul className='grid content-start gap-10 tracking-wide'>
                <li className='grid gap-2'>
                  <h4 className='font-medium text-xl'>
                    Alberta Drone Specialists
                  </h4>

                  <div className='grid mt-1'>
                    <LinkButton 
                      text='View'
                      href='https://abdronespecialists.ca/'
                    />
                  </div>
                </li>

                <li className='grid gap-2'>
                  <h4 className='font-medium text-xl'>
                    BridgeIT Tech Solutions
                  </h4>

                  <div className='grid mt-1'>
                    <LinkButton 
                      text='View'
                      href='https://bridgeittech.ca/'
                    />
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* contact */}
        <section className='grid'>
          <div className='grid gap-10 content-start px-5 py-10 w-full max-w-screen-lg'>
            <img
              src='img/spacecat.svg'
              alt='stranded lab cat wandering on space, thinking about its life choices (assuming it had one)'
              className='justify-self-center w-full max-w-[320px]'
            />

            <div>
              <h2 className='font-light text-4xl tracking-wide'>Contact</h2>
            </div>
          </div>
        </section>
      </main>

      <footer>

      </footer>
    </div>
  )
}
